name: monad-challenges-code
version: "0.1.0.0"
synopsis: The best way to learn monads
description: Series of challenges to help build intuition about monads
category: Education
author: Doug Beardsley
maintainer: mightybyte@gmail.com
license: BSD3
other-extensions:
  - Trustworthy
  - CPP
  - NoImplicitPrelude
  - BangPatterns
dependencies:
  - base >=4 && <5
library:
  source-dirs: src
